# Generated by Django 4.0.6 on 2022-07-07 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=900)),
                ('content_html', models.PositiveBigIntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('date_published', models.DateField()),
                ('author', models.CharField(max_length=500)),
            ],
        ),
    ]
